# Generated by Django 3.2.25 on 2026-02-18 14:32

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('ALUNO', 'Aluno'), ('ENCARREGADO', 'Encarregado'), ('MOTORISTA', 'Motorista')], default='ADMIN', max_length=20)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Salário do usuário (se vazio, aplica valor padrão).', max_digits=10, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Os grupos aos quais este usuário pertence.', related_name='custom_user_groups', to='auth.Group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='custom_user_permissions', to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
