# Generated by Django 3.2.25 on 2026-03-12 15:28

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('hora_partida', models.TimeField(default=datetime.time(5, 20))),
                ('hora_chegada', models.TimeField(default=datetime.time(7, 0))),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alunos', models.ManyToManyField(blank=True, related_name='rotas_transporte', to='core.Aluno')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('matricula', models.CharField(db_index=True, error_messages={'unique': 'A matrícula do veículo já está em uso.'}, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Matrícula inválida. Ex: ABC-123-XY', regex='^[A-Z]{3}-\\d{3}-[A-Z]{2}$')])),
                ('capacidade', models.PositiveIntegerField(help_text='Número máximo de passageiros', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50, message='A capacidade máxima é 50 passageiros.')])),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quilometragem_atual', models.PositiveIntegerField(default=0, help_text='Quilometragem actual do veículo')),
                ('data_ultima_revisao', models.DateField(blank=True, null=True)),
                ('km_proxima_revisao', models.PositiveIntegerField(default=10000, help_text='Quilometragem alvo para a próxima revisão')),
                ('data_validade_seguro', models.DateField(help_text='Validade do seguro', null=True)),
                ('data_validade_inspecao', models.DateField(help_text='Validade da inspecção', null=True)),
                ('nr_manifesto', models.CharField(blank=True, max_length=20, null=True)),
                ('data_validade_manifesto', models.DateField(blank=True, help_text='Validade do manifesto', null=True)),
                ('capacidade_tanque', models.PositiveIntegerField(default=80, help_text='Capacidade do tanque em litros')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.motorista')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='TransporteAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EMBARCADO', 'Embarcado'), ('DESEMBARCADO', 'Desembarcado')], default='PENDENTE', max_length=20)),
                ('data', models.DateField(default=datetime.date.today)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='core.aluno')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='transporte.rota')),
            ],
            options={
                'verbose_name': 'Transporte de Aluno',
                'verbose_name_plural': 'Transportes de Alunos',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='transporte.veiculo'),
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva')], default='PREVENTIVA', max_length=20)),
                ('descricao', models.TextField(help_text='Ex: Troca de óleo, travões')),
                ('data_inicio', models.DateField()),
                ('quilometragem_no_momento_revisao', models.PositiveIntegerField(default=0)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('concluida', models.BooleanField(default=False)),
                ('km_proxima_revisao', models.PositiveIntegerField(default=7000)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='transporte.veiculo')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('quilometragem_no_ato', models.PositiveIntegerField(default=0, help_text='Quilometragem no momento do abastecimento')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posto_combustivel', models.CharField(max_length=100)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimento', to='transporte.veiculo')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-data', '-quilometragem_no_ato'],
            },
        ),
        migrations.AddConstraint(
            model_name='transportealuno',
            constraint=models.UniqueConstraint(fields=('aluno', 'rota', 'data'), name='unique_transporte_aluno_por_dia'),
        ),
    ]
