# Generated by Django 3.2.25 on 2026-02-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_manutencao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manutencao',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
        migrations.AddField(
            model_name='manutencao',
            name='data_ultima_revisao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='km_proxima_revisao',
            field=models.PositiveIntegerField(default=7000),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='quilometragem_no_momento_revisao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_ultima_revisao',
            field=models.DateField(blank=True, help_text='Data da ultima revisao', null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='km_proxima_revisao',
            field=models.PositiveIntegerField(default=10000, help_text='Quilometragem para a proxima revisao'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='quilometragem_atual',
            field=models.PositiveIntegerField(default=0, help_text='Quilometragem atual do veiculo'),
        ),
    ]
