# Generated by Django 3.2.25 on 2026-02-27 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_auto_20260224_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade',
            field=models.PositiveIntegerField(help_text='Número máximo de passageiros', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50, message='A capacidade do veículo deve ser menor ou igual a 50.')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='matricula',
            field=models.CharField(db_index=True, error_messages={'unique': 'A matrícula do veículo já está em uso.'}, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Placa inválida. Ex: ABC-123-XY', regex='^[A-Z]{3}-\\d{3}-[A-Z]{2}$')]),
        ),
        migrations.AddConstraint(
            model_name='transportealuno',
            constraint=models.UniqueConstraint(fields=('aluno', 'rota'), name='unique_transporte_aluno_diario'),
        ),
    ]
