# Generated by Django 3.2.25 on 2026-02-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_auto_20260227_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='data_validade_inspecao',
            field=models.DateField(help_text='Data de validade da inspeção do veiculo', null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_validade_manifesto',
            field=models.DateField(blank=True, help_text='Data de validade do manifesto do veículo', null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_validade_seguro',
            field=models.DateField(help_text='Data de validade do seguro do veiculo', null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='nr_manifesto',
            field=models.CharField(blank=True, help_text='Número do manifesto do veículo', max_length=20, null=True),
        ),
    ]
