# Generated by Django 3.2.25 on 2026-02-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0005_auto_20260227_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('quilometragem_no_ato', models.PositiveIntegerField(default=0, help_text='Quilometragem do veículo no momento do abastecimento')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posto_combustivel', models.CharField(max_length=100)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='transporte.veiculo')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-data', '-quilometragem_no_ato'],
            },
        ),
    ]
