# Generated by Django 3.2.25 on 2026-03-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0006_abastecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='quantidade_litros',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimento', to='transporte.veiculo'),
        ),
    ]
