# Generated by Django 3.2.25 on 2026-03-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0007_auto_20260302_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='tipo',
            field=models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva')], default='PREVENTIVA', max_length=20),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='descricao',
            field=models.TextField(help_text='Descreva o servico (ex: Troca de oleo, travoes)'),
        ),
    ]
