# Generated by Django 3.2.25 on 2026-02-18 14:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}[A-Z]{1}$', 'Formato inválido para BI')])),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='MZ', unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('carta_conducao', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato inválido para carta de condução. Use 9 dígitos.', regex='^\\d{9}$')])),
                ('validade_da_carta', models.DateField(null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'MOTORISTA'}, on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encarregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrBI', models.CharField(db_index=True, help_text='Número de bilhete de identidade', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}[A-Z]{1}$', 'Formato inválido para BI')])),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='MZ', unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'ENCARREGADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='encarregado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}[A-Z]{1}$', 'Formato inválido para BI')])),
                ('escola_dest', models.CharField(db_index=True, max_length=255)),
                ('classe', models.CharField(max_length=25)),
                ('mensalidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encarregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.encarregado')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
