# Generated by Django 3.2.25 on 2026-03-12 15:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'Este email já está em uso.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='O campo de email deve conter um endereço de email válido.')])),
                ('nome', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('GESTOR', 'Gestor'), ('MOTORISTA', 'Motorista'), ('MONITOR', 'Monitor'), ('ENCARREGADO', 'Encarregado'), ('ALUNO', 'Aluno')], db_index=True, default='ADMIN', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='Os grupos aos quais este utilizador pertence.', related_name='custom_user_groups', to='auth.Group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas para este utilizador.', related_name='custom_user_permissions', to='auth.Permission')),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(db_index=True, help_text='Número de bilhete de identidade', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido para BI. Use 12 dígitos seguidos de 1 letra maiúscula.', regex='^\\d{12}[A-Z]{1}$')])),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='MZ', unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('carta_conducao', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido para carta de condução. Use 9 dígitos.', regex='^\\d{9}$')])),
                ('validade_da_carta', models.DateField(null=True)),
                ('salario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('user', models.OneToOneField(limit_choices_to={'role': 'MOTORISTA'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_motorista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(db_index=True, help_text='Número de bilhete de identidade', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido para BI. Use 12 dígitos seguidos de 1 letra maiúscula.', regex='^\\d{12}[A-Z]{1}$')])),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='MZ', unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('salario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('user', models.OneToOneField(limit_choices_to={'role': 'MONITOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_monitor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(db_index=True, help_text='Número de bilhete de identidade', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido para BI. Use 12 dígitos seguidos de 1 letra maiúscula.', regex='^\\d{12}[A-Z]{1}$')])),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='MZ', unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('departamento', models.CharField(choices=[('FROTA', 'Gestão de Frota'), ('ACADEMICO', 'Gestão Académica'), ('FINANCEIRO', 'Financeiro'), ('GERAL', 'Geral')], db_index=True, default='GERAL', help_text='Área de responsabilidade do gestor', max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('motoristas_supervisionados', models.ManyToManyField(blank=True, help_text='Motoristas sob supervisão deste gestor', related_name='gestores', to='core.Motorista')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'GESTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gestor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
            },
        ),
        migrations.CreateModel(
            name='Encarregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(db_index=True, help_text='Número de bilhete de identidade', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido para BI. Use 12 dígitos seguidos de 1 letra maiúscula.', regex='^\\d{12}[A-Z]{1}$')])),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='MZ', unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'ENCARREGADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_encarregado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encarregado',
                'verbose_name_plural': 'Encarregados',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(db_index=True, help_text='Número de bilhete de identidade', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido para BI. Use 12 dígitos seguidos de 1 letra maiúscula.', regex='^\\d{12}[A-Z]{1}$')])),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='MZ', unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola_dest', models.CharField(db_index=True, max_length=255)),
                ('classe', models.CharField(max_length=25)),
                ('mensalidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor base da mensalidade do aluno', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('encarregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.encarregado')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='idx_user_role_active'),
        ),
    ]
