# Generated by Django 3.2.25 on 2026-03-12 15:28

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
                'unique_together': {('nome', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_vencimento', models.PositiveIntegerField(default=5, help_text='Dia do mês em que a mensalidade vence')),
                ('dia_limite_pagamento', models.PositiveIntegerField(default=10, help_text='Último dia para pagamento sem multa')),
                ('valor_multa_fixa', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Valor em MT aplicado após o vencimento', max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuração Financeira',
                'verbose_name_plural': 'Configurações Financeiras',
            },
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referente', models.DateField(db_index=True)),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('multa_atraso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_pago_acumulado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('data_ultimo_pagamento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO_PARCIAL', 'Pago Parcialmente'), ('PAGO', 'Pago Totalmente'), ('ATRASADO', 'Em Atraso'), ('ISENTO', 'Isento/Bolsa')], default='PENDENTE', max_length=20)),
                ('nr_fatura', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_mensalidades', to='core.aluno')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
                'ordering': ['-mes_referente'],
                'unique_together': {('aluno', 'mes_referente')},
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('metodo', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência/NIB'), ('CARTAO', 'Cartão de Débito/Crédito'), ('OUTRO', 'Outro')], default='TRANSFERENCIA', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15)),
                ('referencia_externa_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='core.aluno')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoria')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_recibo', models.CharField(editable=False, max_length=20, unique=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='financeiro/recibos/%Y/%m')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('mensalidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo_emitido', to='financeiro.mensalidade')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
            },
        ),
        migrations.CreateModel(
            name='LogNotificacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=10)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('destino', models.CharField(max_length=100)),
                ('resposta_server', models.TextField(blank=True, null=True)),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='financeiro.mensalidade')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificação',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuit', models.CharField(help_text='Número de Identificação Tributária (9 dígitos)', max_length=9, unique=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subsidio_transporte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('data_admissao', models.DateField(auto_now_add=True)),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('gestor_perfil', models.OneToOneField(blank=True, help_text='Preencher apenas se o utilizador tiver role GESTOR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dados_financeiros', to='core.gestor')),
                ('monitor_perfil', models.OneToOneField(blank=True, help_text='Preencher apenas se o utilizador tiver role MONITOR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dados_financeiros', to='core.monitor')),
                ('motorista_perfil', models.OneToOneField(blank=True, help_text='Preencher apenas se o utilizador tiver role MOTORISTA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dados_financeiros', to='core.motorista')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='DespesaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMBUSTIVEL', 'Combustível'), ('MANUTENCAO', 'Manutenção/Oficina'), ('DOCUMENTACAO', 'Seguros/Inspecção/Taxas'), ('LIMPEZA', 'Lavagem/Limpeza')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=datetime.date.today)),
                ('km_atual', models.PositiveIntegerField(blank=True, help_text='Quilometragem para controlo de consumo', null=True)),
                ('transacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_veiculo', to='financeiro.transacao')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='transporte.veiculo')),
            ],
            options={
                'verbose_name': 'Despesa de Veículo',
                'verbose_name_plural': 'Despesas de Veículos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='DespesaGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'DESPESA'}, on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoria')),
                ('transacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_geral', to='financeiro.transacao')),
            ],
            options={
                'verbose_name': 'Despesa Geral',
                'verbose_name_plural': 'Despesas Gerais',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='BalancoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Primeiro dia do mês', unique=True)),
                ('data_fecho', models.DateTimeField(auto_now_add=True)),
                ('total_receitas_previstas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_receitas_pagas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_despesas_gerais', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_despesas_frota', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_folha_salarial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lucro_prejuizo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('finalizado', models.BooleanField(default=False)),
                ('transacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balanco_mensal', to='financeiro.transacao')),
            ],
            options={
                'verbose_name': 'Balanço Mensal',
                'verbose_name_plural': 'Balanços Mensais',
                'ordering': ['-mes_referencia'],
            },
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referente', models.DateField(help_text='Primeiro dia do mês correspondente')),
                ('data_processamento', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=15)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='financeiro.funcionario')),
                ('transacao_vinculada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.transacao')),
            ],
            options={
                'verbose_name': 'Folha de Pagamento',
                'verbose_name_plural': 'Folhas de Pagamento',
                'unique_together': {('funcionario', 'mes_referente')},
            },
        ),
    ]
