# Generated by Django 3.2.25 on 2026-03-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_funcionario_salario_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='metodo',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência Bancária/NIB'), ('CARTAO', 'Cartão de Débito/Crédito'), ('MPESA', 'M-Pesa (Vodacom)'), ('EMOLA', 'e-Mola (Tmcel)'), ('MKESH', 'mKesh (Millennium BIM)'), ('PONTO24', 'Ponto 24 (BCI)'), ('MOVITEL_MONEY', 'Movitel Money'), ('OUTRO', 'Outro')], default='TRANSFERENCIA', max_length=20),
        ),
    ]
