# Generated by Django 3.2.25 on 2026-03-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20260322_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='metodo',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência Bancária/NIB'), ('CARTAO', 'Cartão de Débito/Crédito'), ('MPESA', 'M-Pesa (Vodacom)'), ('EMOLA', 'e-Mola (Movitel)'), ('MKESH', 'mKesh (Tmcel)'), ('PONTO24', 'Ponto 24 (BCI)'), ('OUTRO', 'Outro')], default='TRANSFERENCIA', max_length=20),
        ),
    ]
