# Generated by Django 3.2.25 on 2026-03-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_transacao_metodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='arquivo_pdf',
            new_name='arquivo',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='metodo',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência Bancária/NIB'), ('CARTAO', 'Cartão de Débito/Crédito'), ('MPESA', 'M-Pesa (Vodacom)'), ('EMOLA', 'e-Mola (Tmcel)'), ('MKESH', 'mKesh (Millennium BIM)'), ('PONTO24', 'Ponto 24 (BCI)'), ('MOVITEL_MONEY', 'Movitel Money'), ('OUTRO', 'Outro')], default='TRANSFERENCIA', max_length=20),
        ),
    ]
